sudo: false
language: python
python:
    - "3.4"

notifications:
  email: false

branches:
    only:
        - master

before_install:
  - wget http://repo.continuum.io/miniconda/Miniconda-latest-Linux-x86_64.sh -O miniconda.sh
  - chmod +x miniconda.sh
  - ./miniconda.sh -b
  - export PATH=/home/travis/miniconda/bin:$PATH
  - conda update --yes conda

install: # Prepare system
    - conda install --yes python=$TRAVIS_PYTHON_VERSION numpy scipy nltk scikit-learn pytest bitarray
    - pip install -U pip
    - pip install -e .
    - ./get_data_sets.sh

script: # Test
    - py.test --cov ./ --cov-report term --cov-report xml

after_success:
    - coveralls

